apiVersion: v1
kind: Service
metadata:
  name: todo-list-dockerized-flask-webapp
  labels:
    app: todo-list-dockerized-flask-webapp
spec:
  type: NodePort
  selector:
    app: todo-list-dockerized-flask-webapp
  ports:
  - port: 80
    targetPort: 5000
